[project]
name = "master-thesis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "SALib",
    "numpy",
    "scikit-learn",
    "matplotlib",
    "marimo>=0.11.14",
    "polars>=1.24.0",
    "altair>=5.5.0",
    "networkx>=3.4.2",
    "pyarrow>=8.0.0",
    "sqlalchemy>=2.0.39",
    "numba>=0.61.0",
    "cuda-python>=12.8.0",
]
