[project]
name = "master-thesis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "SALib",
    "numpy",
    "pandas",
    "matplotlib",
    "pyqt6>=6.8.0",
]
