file_out: "results/degroot_deliberation_trials_30_control.csv"
data_loc: "data/a1r.db"
graph: "graphs/soc-astro.edges"
n_trials: 50
n_voters: 
  istart: 51
  istop: 302
  istep: 50
n_candidates: 
  istart: 3
  istop: 3
  istep: 1
condition: "0"
timesteps: 
  start: 1.0
  stop: 151.0
  step: 25.0
bias:
  start: 0.5
  stop: 1.5
  step: 0.3
cand_method: ["SampleVoters", "Voter"]

