file_out: "results/degroot_control_100.csv"
data_loc: "data/a1r.db"
graph: "graphs/soc-astro.edges"
n_trials: 100
n_voters: 
  istart: 31
  istop: 82
  istep: 10
n_candidates: 
  istart: 3
  istop: 7
  istep: 1
condition: "0"
timesteps: 
  start: 1.0
  stop: 151.0
  step: 25.0
bias:
  start: 0.5
  stop: 1.5
  step: 0.3
cand_method: ["SampleVoters", "Voter"]
eval: degroot
credibility: false
sparse: true 
include_knowledge: true
group: false
