file_out: "results/test.csv"
data_loc: "data/a1r.db"
graph: "graphs/soc-astro.edges"
random: true
n_trials: 8
n_voters: 
  istart: 9
  istop: 15
  istep: 2
n_candidates: 
  istart: 3
  istop: 7
  istep: 1
condition: "1"
credibility: 
  should_randomize: false
  value: false 
include_knowledge: 
  should_randomize: false
  value: true 
include_ego: 
  should_randomize: false
  value: true 
sparse: false
timesteps: 
  start: 1.0
  stop: 151.0
  step: 25.0
bias:
  start: 0.8
  stop: 1.5
  step: 0.1
cand_method: ["SampleVoters", "Voter"]
eval: degroot
group: true 

  # meta : parameterBool;
  # substantive : parameterBool;
